version: '3'

services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
